# Generated by Django 5.1.3 on 2024-11-15 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_alter_author_created_at_alter_author_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="books",
            new_name="book",
        ),
    ]
